// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar'];
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb'];
    AButton: typeof import('ant-design-vue/es')['Button'];
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider'];
    AInput: typeof import('ant-design-vue/es')['Input'];
    ALayout: typeof import('ant-design-vue/es')['Layout'];
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter'];
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider'];
    AList: typeof import('ant-design-vue/es')['List'];
    AListItem: typeof import('ant-design-vue/es')['ListItem'];
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta'];
    ASpin: typeof import('ant-design-vue/es')['Spin'];
    ATabPane: typeof import('ant-design-vue/es')['TabPane'];
    ATabs: typeof import('ant-design-vue/es')['Tabs'];
    ATag: typeof import('ant-design-vue/es')['Tag'];
    ATypographyParagraph: typeof import('ant-design-vue/es')['TypographyParagraph'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
